name: Compile Linux Kernel

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        apt-get update && \
        apt-get install -y -q apt-utils dialog  python && \
        apt-get install -y -q sudo aptitude flex bison libncurses5-dev make git exuberant-ctags sparse bc libssl-dev libelf-dev         
        git clone https://github.com/GrowtopiaJaw/aarch64-linux-android-4.9.git -b google --single-branch aarch64-linux-android-4.9
        export PATH=$PWD/aarch64-linux-android-4.9/bin:$PATH
        export CROSS_COMPILE=aarch64-linux-android-
        export ARCH=arm64
        export SUBARCH=arm64


    - name: Compile Kernel
      run: |
        make ARCH=arm64 CROSS_COMPILE=aaarch64-linux-android-  defconfig
        make
    - name: Package Kernel
      run: |
        mkdir -p ~/linux/linux/pack
        cp arch/arm64/boot/Image ~/linux/linux/pack
        cp arch/arm64/boot/dts/*.dtb  ~/linux/linux/pack

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: kernel-artifacts
        path: ~/linux/linux/pack
